### ISSUE TITLE
AYUDA

### ISSUE THREAD

**Issue by Johanx22x** [Makodotpy/Proyecto_Copia_1#1]
Arregleme el aire, estoy en cubiculo 7. @zSnails tambien ocupa ayuda con el de el.
`print("Hello Makodotpy")`
 [DA CLICK AQUI](https://github.com/AliHashemiS)
[My informacion bancaria](https://matias.ma/nsfw/)

**Comment by Johanx22x** [comment]
Ya no, gracias

**Comment by Makodotpy** [comment]
Quién es?
Y cómo sabe que veo aires? jaajja

**Comment by zSnails** [comment]
Tal vez que ve aires no pero algo les hace, eso no es importante ahora

**Comment by Makodotpy** [comment]
Entonces qué es importante ahora, Aaron?

________________________________
De: zSnails ***@***.***>
Enviado: jueves, 25 de mayo de 2023 14:15
Para: Makodotpy/Proyecto_Copia_1 ***@***.***>
Cc: MAIKOL GABRIEL FLORES MADRIGAL ***@***.***>; Comment ***@***.***>
Asunto: Re: [Makodotpy/Proyecto_Copia_1] AYUDA (Issue #1)

Tal vez que ve aires no pero algo les hace, eso no es importante ahora — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented. Message ID: <Makodotpy/Proyecto_Copia_1/issues/1/1563454104@ github. com>
ZjQcmQRYFpfptBannerStart
Este mensaje proviene de un remitente externo
Este mensaje vino de fuera de su organización.

ZjQcmQRYFpfptBannerEnd

Tal vez que ve aires no pero algo les hace, eso no es importante ahora

**Comment by zSnails** [comment]
Las partidas de fortnite que nunca jugamos 😡

**Comment by Johanx22x** [comment]
![Screenshot_2023-03-27-23-22-28-955_com whatsapp](https://github.com/Makodotpy/Proyecto_Copia_1/assets/101372687/eedcba44-5b87-4450-b338-c8ee138218b9)

**Comment by Makodotpy** [comment]
Cieerto
Hace rato de eso mae
________________________________
De: zSnails ***@***.***>
Enviado: jueves, 25 de mayo de 2023 14:44
Para: Makodotpy/Proyecto_Copia_1 ***@***.***>
Cc: MAIKOL GABRIEL FLORES MADRIGAL ***@***.***>; Comment ***@***.***>
Asunto: Re: [Makodotpy/Proyecto_Copia_1] AYUDA (Issue #1)

Las partidas de fortnite que nunca jugamos 😡 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented. Message ID: <Makodotpy/Proyecto_Copia_1/issues/1/1563485611@ github. com>
ZjQcmQRYFpfptBannerStart
Este mensaje proviene de un remitente externo
Este mensaje vino de fuera de su organización.

ZjQcmQRYFpfptBannerEnd

Las partidas de fortnite que nunca jugamos 😡
